// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as main$0 from "../../../../../oso/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "upload:done": main$0.UploadDoneEvent;
            "upload:error": main$0.UploadErrorEvent;
            "upload:folder:start": main$0.UploadFolderStartEvent;
            "upload:progress": main$0.UploadProgressEvent;
        }
    }
}
