// Typed custom events generated by `wails3 generate bindings`
/// <reference path="../bindings/github.com/wailsapp/wails/v3/internal/eventdata.d.ts" />

// See https://svelte.dev/docs/kit/types#app.d.ts
// for information about these interfaces
declare global {
	namespace App {
		// interface Error {}
		// interface Locals {}
		// interface PageData {}
		// interface PageState {}
		// interface Platform {}
	}
}

export {};
