// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the Wails service exposing all S3 operations to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdates opens the update window and runs the check, download and
 * install flow. Progress and errors are shown in that window.
 */
export function CheckForUpdates(): $CancellablePromise<void> {
    return $Call.ByID(2675659504);
}

/**
 * Connect verifies a configuration, saves it as a profile and makes it the
 * active connection. A profile with the same endpoint and access key is reused.
 */
export function Connect(cfg: $models.S3Config): $CancellablePromise<void> {
    return $Call.ByID(164877153, cfg);
}

/**
 * CopyFolder recursively copies all objects under a prefix to a new destination
 */
export function CopyFolder(srcBucket: string, srcPrefix: string, dstBucket: string, dstPrefix: string): $CancellablePromise<void> {
    return $Call.ByID(1081183832, srcBucket, srcPrefix, dstBucket, dstPrefix);
}

/**
 * CopyObject copies an object from src to dst
 */
export function CopyObject(srcBucket: string, srcKey: string, dstBucket: string, dstKey: string): $CancellablePromise<void> {
    return $Call.ByID(3419807963, srcBucket, srcKey, dstBucket, dstKey);
}

/**
 * CreateBucket creates a new S3 bucket after validating the name
 */
export function CreateBucket(name: string): $CancellablePromise<void> {
    return $Call.ByID(393487511, name);
}

/**
 * CreateFolder creates an S3 folder marker
 */
export function CreateFolder(bucket: string, prefix: string, folderName: string): $CancellablePromise<void> {
    return $Call.ByID(1403526973, bucket, prefix, folderName);
}

/**
 * DeleteBucket deletes a bucket. S3 only deletes empty buckets, so with
 * deleteContents every object in it is removed first.
 */
export function DeleteBucket(name: string, deleteContents: boolean): $CancellablePromise<void> {
    return $Call.ByID(3728638004, name, deleteContents);
}

/**
 * DeleteFolder recursively deletes all objects under a prefix
 */
export function DeleteFolder(bucket: string, prefix: string): $CancellablePromise<void> {
    return $Call.ByID(127207050, bucket, prefix);
}

/**
 * DeleteObject deletes a single S3 object
 */
export function DeleteObject(bucket: string, key: string): $CancellablePromise<void> {
    return $Call.ByID(3131505817, bucket, key);
}

/**
 * DeleteObjects deletes multiple S3 objects one by one (compatible with all S3 backends)
 */
export function DeleteObjects(bucket: string, keys: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(3202360414, bucket, keys);
}

/**
 * DeleteProfile removes a saved profile; deleting the active one disconnects
 */
export function DeleteProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(2457157279, id);
}

/**
 * Disconnect clears the active S3 connection. The profiles stay saved, and the
 * app starts disconnected until one is chosen again.
 */
export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(3864343059);
}

/**
 * DownloadObject downloads an S3 object to a local path
 */
export function DownloadObject(bucket: string, key: string, destPath: string): $CancellablePromise<void> {
    return $Call.ByID(4258742462, bucket, key, destPath);
}

/**
 * GetActiveProfileID returns the ID of the connected profile, or an empty string
 */
export function GetActiveProfileID(): $CancellablePromise<string> {
    return $Call.ByID(3651291183);
}

/**
 * GetAvailableUpdate silently checks for a newer release and returns its
 * version, or an empty string when the app is up to date.
 */
export function GetAvailableUpdate(): $CancellablePromise<string> {
    return $Call.ByID(4024198311);
}

/**
 * GetDownloadsFolder returns the system Downloads folder path
 */
export function GetDownloadsFolder(): $CancellablePromise<string> {
    return $Call.ByID(518210492);
}

/**
 * GetObjectProperties returns the metadata of an object. Tags are optional:
 * backends without tagging support simply report none.
 */
export function GetObjectProperties(bucket: string, key: string): $CancellablePromise<$models.ObjectProperties | null> {
    return $Call.ByID(1906098353, bucket, key);
}

/**
 * GetPresignedURL generates a presigned download URL for an S3 object
 */
export function GetPresignedURL(bucket: string, key: string, expirySeconds: number): $CancellablePromise<string> {
    return $Call.ByID(3273064529, bucket, key, expirySeconds);
}

/**
 * GetSavedConfig returns the configuration of the active connection
 */
export function GetSavedConfig(): $CancellablePromise<$models.S3Config | null> {
    return $Call.ByID(3217435348);
}

/**
 * GetSettings returns application settings (with defaults)
 */
export function GetSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(2554697378);
}

/**
 * GetVersion returns the app version
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(1049863377);
}

/**
 * IsConnected returns true if currently connected to S3
 */
export function IsConnected(): $CancellablePromise<boolean> {
    return $Call.ByID(236330520);
}

/**
 * ListBuckets returns all S3 buckets
 */
export function ListBuckets(): $CancellablePromise<$models.Bucket[] | null> {
    return $Call.ByID(175992912);
}

/**
 * ListObjects lists objects in a bucket with prefix-based filtering and pagination
 */
export function ListObjects(bucket: string, prefix: string, continuationToken: string, maxKeys: number): $CancellablePromise<$models.ListObjectsResult | null> {
    return $Call.ByID(103960399, bucket, prefix, continuationToken, maxKeys);
}

/**
 * ListProfiles returns the saved profiles, preceded by the environment
 * profile when the app was configured through S3_* variables
 */
export function ListProfiles(): $CancellablePromise<$models.ConnectionProfile[] | null> {
    return $Call.ByID(1957526603);
}

/**
 * MoveFolder recursively moves all objects under a prefix (copy + delete)
 */
export function MoveFolder(srcBucket: string, srcPrefix: string, dstBucket: string, dstPrefix: string): $CancellablePromise<void> {
    return $Call.ByID(3833907176, srcBucket, srcPrefix, dstBucket, dstPrefix);
}

/**
 * MoveObject moves an object (copy + delete)
 */
export function MoveObject(srcBucket: string, srcKey: string, dstBucket: string, dstKey: string): $CancellablePromise<void> {
    return $Call.ByID(1877564011, srcBucket, srcKey, dstBucket, dstKey);
}

/**
 * OpenDirectoryDialog opens a folder-picker dialog
 */
export function OpenDirectoryDialog(): $CancellablePromise<string> {
    return $Call.ByID(1188724780);
}

/**
 * OpenFileDialog opens a single-file picker dialog
 */
export function OpenFileDialog(): $CancellablePromise<string> {
    return $Call.ByID(4196526771);
}

/**
 * OpenMultipleFilesDialog opens a multi-file picker dialog
 */
export function OpenMultipleFilesDialog(): $CancellablePromise<string[] | null> {
    return $Call.ByID(4031060776);
}

/**
 * OpenSettingsWindow shows the settings window, creating it on first use, and
 * selects the given section ("general", "connections", "about"; empty keeps the
 * current one). It returns false in server mode, where there are no native
 * windows and the frontend opens the settings page itself.
 */
export function OpenSettingsWindow(section: string): $CancellablePromise<boolean> {
    return $Call.ByID(3185921024, section);
}

/**
 * SaveFileDialog opens a save-file dialog
 */
export function SaveFileDialog(defaultName: string): $CancellablePromise<string> {
    return $Call.ByID(1166008166, defaultName);
}

/**
 * SaveProfile creates a profile (empty ID) or updates an existing one. Changes
 * to the active profile are verified first and take effect immediately.
 */
export function SaveProfile(profile: $models.ConnectionProfile): $CancellablePromise<$models.ConnectionProfile> {
    return $Call.ByID(406053493, profile);
}

/**
 * SaveSettings persists application settings and tells every window
 */
export function SaveSettings(settings: $models.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(1949631069, settings);
}

/**
 * SearchObjects searches immediate children under a prefix across all paginated pages.
 * Results are folder-first and capped by maxResults for responsiveness.
 */
export function SearchObjects(bucket: string, prefix: string, query: string, maxResults: number): $CancellablePromise<$models.S3Object[] | null> {
    return $Call.ByID(4220472151, bucket, prefix, query, maxResults);
}

/**
 * SwitchProfile connects to another profile. When the new connection fails,
 * the current one stays in place.
 */
export function SwitchProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(3869054282, id);
}

/**
 * TestConnection checks a configuration without changing the active connection
 */
export function TestConnection(cfg: $models.S3Config): $CancellablePromise<void> {
    return $Call.ByID(1257240193, cfg);
}

/**
 * UpdateObjectProperties replaces the content type and user metadata of an
 * object by copying it onto itself. The other headers, the storage class and
 * the tags are carried over.
 */
export function UpdateObjectProperties(bucket: string, key: string, contentType: string, metadata: { [_ in string]?: string } | null): $CancellablePromise<void> {
    return $Call.ByID(358085538, bucket, key, contentType, metadata);
}

/**
 * UploadFile uploads a local file (or folder) to S3, emitting progress events.
 */
export function UploadFile(bucket: string, prefix: string, localPath: string): $CancellablePromise<void> {
    return $Call.ByID(3284072274, bucket, prefix, localPath);
}

/**
 * UploadFiles uploads multiple local files or folders sequentially. A mixed
 * selection, as produced by dropping files onto the window, is announced as
 * one batch covering every file inside the folders.
 */
export function UploadFiles(bucket: string, prefix: string, localPaths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(1184827635, bucket, prefix, localPaths);
}
