// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the Wails service exposing all S3 operations to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdates opens the update window and runs the check, download and
 * install flow. Progress and errors are shown in that window.
 */
export function CheckForUpdates(): $CancellablePromise<void> {
    return $Call.ByID(2675659504);
}

/**
 * Connect connects to S3 with the given configuration and tests it
 */
export function Connect(cfg: $models.S3Config): $CancellablePromise<void> {
    return $Call.ByID(164877153, cfg);
}

/**
 * CopyFolder recursively copies all objects under a prefix to a new destination
 */
export function CopyFolder(srcBucket: string, srcPrefix: string, dstBucket: string, dstPrefix: string): $CancellablePromise<void> {
    return $Call.ByID(1081183832, srcBucket, srcPrefix, dstBucket, dstPrefix);
}

/**
 * CopyObject copies an object from src to dst
 */
export function CopyObject(srcBucket: string, srcKey: string, dstBucket: string, dstKey: string): $CancellablePromise<void> {
    return $Call.ByID(3419807963, srcBucket, srcKey, dstBucket, dstKey);
}

/**
 * CreateBucket creates a new S3 bucket after validating the name
 */
export function CreateBucket(name: string): $CancellablePromise<void> {
    return $Call.ByID(393487511, name);
}

/**
 * CreateFolder creates an S3 folder marker
 */
export function CreateFolder(bucket: string, prefix: string, folderName: string): $CancellablePromise<void> {
    return $Call.ByID(1403526973, bucket, prefix, folderName);
}

/**
 * DeleteFolder recursively deletes all objects under a prefix
 */
export function DeleteFolder(bucket: string, prefix: string): $CancellablePromise<void> {
    return $Call.ByID(127207050, bucket, prefix);
}

/**
 * DeleteObject deletes a single S3 object
 */
export function DeleteObject(bucket: string, key: string): $CancellablePromise<void> {
    return $Call.ByID(3131505817, bucket, key);
}

/**
 * DeleteObjects deletes multiple S3 objects one by one (compatible with all S3 backends)
 */
export function DeleteObjects(bucket: string, keys: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(3202360414, bucket, keys);
}

/**
 * Disconnect clears the active S3 connection
 */
export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(3864343059);
}

/**
 * DownloadObject downloads an S3 object to a local path
 */
export function DownloadObject(bucket: string, key: string, destPath: string): $CancellablePromise<void> {
    return $Call.ByID(4258742462, bucket, key, destPath);
}

/**
 * GetAvailableUpdate silently checks for a newer release and returns its
 * version, or an empty string when the app is up to date.
 */
export function GetAvailableUpdate(): $CancellablePromise<string> {
    return $Call.ByID(4024198311);
}

/**
 * GetDownloadsFolder returns the system Downloads folder path
 */
export function GetDownloadsFolder(): $CancellablePromise<string> {
    return $Call.ByID(518210492);
}

/**
 * GetPresignedURL generates a presigned download URL for an S3 object
 */
export function GetPresignedURL(bucket: string, key: string, expirySeconds: number): $CancellablePromise<string> {
    return $Call.ByID(3273064529, bucket, key, expirySeconds);
}

/**
 * GetSavedConfig returns the saved S3 configuration
 */
export function GetSavedConfig(): $CancellablePromise<$models.S3Config | null> {
    return $Call.ByID(3217435348);
}

/**
 * GetSettings returns application settings (with defaults)
 */
export function GetSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(2554697378);
}

/**
 * GetVersion returns the app version
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(1049863377);
}

/**
 * IsConnected returns true if currently connected to S3
 */
export function IsConnected(): $CancellablePromise<boolean> {
    return $Call.ByID(236330520);
}

/**
 * ListBuckets returns all S3 buckets
 */
export function ListBuckets(): $CancellablePromise<$models.Bucket[] | null> {
    return $Call.ByID(175992912);
}

/**
 * ListObjects lists objects in a bucket with prefix-based filtering and pagination
 */
export function ListObjects(bucket: string, prefix: string, continuationToken: string, maxKeys: number): $CancellablePromise<$models.ListObjectsResult | null> {
    return $Call.ByID(103960399, bucket, prefix, continuationToken, maxKeys);
}

/**
 * MoveFolder recursively moves all objects under a prefix (copy + delete)
 */
export function MoveFolder(srcBucket: string, srcPrefix: string, dstBucket: string, dstPrefix: string): $CancellablePromise<void> {
    return $Call.ByID(3833907176, srcBucket, srcPrefix, dstBucket, dstPrefix);
}

/**
 * MoveObject moves an object (copy + delete)
 */
export function MoveObject(srcBucket: string, srcKey: string, dstBucket: string, dstKey: string): $CancellablePromise<void> {
    return $Call.ByID(1877564011, srcBucket, srcKey, dstBucket, dstKey);
}

/**
 * OpenDirectoryDialog opens a folder-picker dialog
 */
export function OpenDirectoryDialog(): $CancellablePromise<string> {
    return $Call.ByID(1188724780);
}

/**
 * OpenFileDialog opens a single-file picker dialog
 */
export function OpenFileDialog(): $CancellablePromise<string> {
    return $Call.ByID(4196526771);
}

/**
 * OpenMultipleFilesDialog opens a multi-file picker dialog
 */
export function OpenMultipleFilesDialog(): $CancellablePromise<string[] | null> {
    return $Call.ByID(4031060776);
}

/**
 * SaveConfig persists the S3 config to disk
 */
export function SaveConfig(cfg: $models.S3Config): $CancellablePromise<void> {
    return $Call.ByID(3442292638, cfg);
}

/**
 * SaveFileDialog opens a save-file dialog
 */
export function SaveFileDialog(defaultName: string): $CancellablePromise<string> {
    return $Call.ByID(1166008166, defaultName);
}

/**
 * SaveSettings persists application settings
 */
export function SaveSettings(settings: $models.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(1949631069, settings);
}

/**
 * SearchObjects searches immediate children under a prefix across all paginated pages.
 * Results are folder-first and capped by maxResults for responsiveness.
 */
export function SearchObjects(bucket: string, prefix: string, query: string, maxResults: number): $CancellablePromise<$models.S3Object[] | null> {
    return $Call.ByID(4220472151, bucket, prefix, query, maxResults);
}

/**
 * UploadFile uploads a local file (or folder) to S3, emitting progress events.
 */
export function UploadFile(bucket: string, prefix: string, localPath: string): $CancellablePromise<void> {
    return $Call.ByID(3284072274, bucket, prefix, localPath);
}

/**
 * UploadFiles uploads multiple local files or folders sequentially.
 */
export function UploadFiles(bucket: string, prefix: string, localPaths: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(1184827635, bucket, prefix, localPaths);
}
