// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppSettings holds application settings
 */
export interface AppSettings {
    "defaultDownloadPath": string;
    "askBeforeDownload": boolean;
    "showFileDetails": boolean;
    "pageSize": number;
    "theme": string;
}

/**
 * Bucket represents an S3 bucket
 */
export interface Bucket {
    "name": string;
    "creationDate": string;
}

/**
 * ConnectionProfile is one saved S3 account
 */
export interface ConnectionProfile {
    "id": string;
    "name": string;
    "endpoint": string;
    "accessKey": string;
    "secretKey": string;
    "region": string;

    /**
     * ReadOnly marks the environment profile, which cannot be edited or deleted
     */
    "readOnly": boolean;
}

/**
 * FilesDroppedEvent reports files dragged from the OS onto the main window
 */
export interface FilesDroppedEvent {
    "paths": string[] | null;

    /**
     * Prefix is the folder the files were dropped on; empty means the folder
     * currently shown
     */
    "prefix": string;
}

/**
 * ListObjectsResult holds paginated listing results
 */
export interface ListObjectsResult {
    "objects": S3Object[] | null;
    "nextContinuationToken": string;
    "hasMore": boolean;
}

/**
 * ObjectProperties holds the HeadObject details and tags of one object
 */
export interface ObjectProperties {
    "bucket": string;
    "key": string;
    "size": number;
    "lastModified": string;
    "contentType": string;
    "etag": string;
    "storageClass": string;
    "versionId": string;
    "cacheControl": string;
    "contentDisposition": string;
    "contentEncoding": string;
    "metadata": { [_ in string]?: string } | null;
    "tags": { [_ in string]?: string } | null;
}

/**
 * ProfilesChangedEvent carries the connection state after a profile change
 */
export interface ProfilesChangedEvent {
    "activeId": string;
    "connected": boolean;
}

/**
 * S3Config holds S3 connection configuration
 */
export interface S3Config {
    "endpoint": string;
    "accessKey": string;
    "secretKey": string;
    "region": string;
}

/**
 * S3Object represents a file or folder in S3
 */
export interface S3Object {
    "key": string;
    "name": string;
    "size": number;
    "lastModified": string;
    "isFolder": boolean;
    "etag": string;
}

/**
 * UploadDoneEvent reports a finished file upload
 */
export interface UploadDoneEvent {
    "key": string;
}

/**
 * UploadErrorEvent reports a failed file upload
 */
export interface UploadErrorEvent {
    "key": string;
    "error": string;
}

/**
 * UploadFolderStartEvent announces how many files a folder upload contains
 */
export interface UploadFolderStartEvent {
    "total": number;
}

/**
 * UploadProgressEvent reports per-file upload progress (0-100)
 */
export interface UploadProgressEvent {
    "key": string;
    "progress": number;
}
