// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppSettings holds application settings
 */
export interface AppSettings {
    "defaultDownloadPath": string;
    "askBeforeDownload": boolean;
    "showFileDetails": boolean;
    "pageSize": number;
}

/**
 * Bucket represents an S3 bucket
 */
export interface Bucket {
    "name": string;
    "creationDate": string;
}

/**
 * ListObjectsResult holds paginated listing results
 */
export interface ListObjectsResult {
    "objects": S3Object[] | null;
    "nextContinuationToken": string;
    "hasMore": boolean;
}

/**
 * S3Config holds S3 connection configuration
 */
export interface S3Config {
    "endpoint": string;
    "accessKey": string;
    "secretKey": string;
    "region": string;
}

/**
 * S3Object represents a file or folder in S3
 */
export interface S3Object {
    "key": string;
    "name": string;
    "size": number;
    "lastModified": string;
    "isFolder": boolean;
    "etag": string;
}

/**
 * UploadDoneEvent reports a finished file upload
 */
export interface UploadDoneEvent {
    "key": string;
}

/**
 * UploadErrorEvent reports a failed file upload
 */
export interface UploadErrorEvent {
    "key": string;
    "error": string;
}

/**
 * UploadFolderStartEvent announces how many files a folder upload contains
 */
export interface UploadFolderStartEvent {
    "total": number;
}

/**
 * UploadProgressEvent reports per-file upload progress (0-100)
 */
export interface UploadProgressEvent {
    "key": string;
    "progress": number;
}
