// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppSettings holds application settings
 */
export class AppSettings {
    "defaultDownloadPath": string;
    "askBeforeDownload": boolean;
    "showFileDetails": boolean;
    "pageSize": number;

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("defaultDownloadPath" in $$source)) {
            this["defaultDownloadPath"] = "";
        }
        if (!("askBeforeDownload" in $$source)) {
            this["askBeforeDownload"] = false;
        }
        if (!("showFileDetails" in $$source)) {
            this["showFileDetails"] = false;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

/**
 * Bucket represents an S3 bucket
 */
export class Bucket {
    "name": string;
    "creationDate": string;

    /** Creates a new Bucket instance. */
    constructor($$source: Partial<Bucket> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("creationDate" in $$source)) {
            this["creationDate"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Bucket instance from a string or object.
     */
    static createFrom($$source: any = {}): Bucket {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Bucket($$parsedSource as Partial<Bucket>);
    }
}

/**
 * ListObjectsResult holds paginated listing results
 */
export class ListObjectsResult {
    "objects": S3Object[];
    "nextContinuationToken": string;
    "hasMore": boolean;

    /** Creates a new ListObjectsResult instance. */
    constructor($$source: Partial<ListObjectsResult> = {}) {
        if (!("objects" in $$source)) {
            this["objects"] = [];
        }
        if (!("nextContinuationToken" in $$source)) {
            this["nextContinuationToken"] = "";
        }
        if (!("hasMore" in $$source)) {
            this["hasMore"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListObjectsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ListObjectsResult {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("objects" in $$parsedSource) {
            $$parsedSource["objects"] = $$createField0_0($$parsedSource["objects"]);
        }
        return new ListObjectsResult($$parsedSource as Partial<ListObjectsResult>);
    }
}

/**
 * S3Config holds S3 connection configuration
 */
export class S3Config {
    "endpoint": string;
    "accessKey": string;
    "secretKey": string;
    "region": string;

    /** Creates a new S3Config instance. */
    constructor($$source: Partial<S3Config> = {}) {
        if (!("endpoint" in $$source)) {
            this["endpoint"] = "";
        }
        if (!("accessKey" in $$source)) {
            this["accessKey"] = "";
        }
        if (!("secretKey" in $$source)) {
            this["secretKey"] = "";
        }
        if (!("region" in $$source)) {
            this["region"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new S3Config instance from a string or object.
     */
    static createFrom($$source: any = {}): S3Config {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new S3Config($$parsedSource as Partial<S3Config>);
    }
}

/**
 * S3Object represents a file or folder in S3
 */
export class S3Object {
    "key": string;
    "name": string;
    "size": number;
    "lastModified": string;
    "isFolder": boolean;
    "etag": string;

    /** Creates a new S3Object instance. */
    constructor($$source: Partial<S3Object> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("lastModified" in $$source)) {
            this["lastModified"] = "";
        }
        if (!("isFolder" in $$source)) {
            this["isFolder"] = false;
        }
        if (!("etag" in $$source)) {
            this["etag"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new S3Object instance from a string or object.
     */
    static createFrom($$source: any = {}): S3Object {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new S3Object($$parsedSource as Partial<S3Object>);
    }
}

// Private type creation functions
const $$createType0 = S3Object.createFrom;
const $$createType1 = $Create.Array($$createType0);
