// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:main.S3Config):Promise<void>;

export function CopyFolder(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CopyObject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CreateBucket(arg1:string):Promise<void>;

export function CreateFolder(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteFolder(arg1:string,arg2:string):Promise<void>;

export function DeleteObject(arg1:string,arg2:string):Promise<void>;

export function DeleteObjects(arg1:string,arg2:Array<string>):Promise<void>;

export function Disconnect():Promise<void>;

export function DownloadObject(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetDownloadsFolder():Promise<string>;

export function GetPresignedURL(arg1:string,arg2:string,arg3:number):Promise<string>;

export function GetSavedConfig():Promise<main.S3Config>;

export function GetSettings():Promise<main.AppSettings>;

export function GetVersion():Promise<string>;

export function IsConnected():Promise<boolean>;

export function ListBuckets():Promise<Array<main.Bucket>>;

export function ListObjects(arg1:string,arg2:string,arg3:string,arg4:number):Promise<main.ListObjectsResult>;

export function MoveFolder(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function MoveObject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function OpenMultipleFilesDialog():Promise<Array<string>>;

export function SaveConfig(arg1:main.S3Config):Promise<void>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SaveSettings(arg1:main.AppSettings):Promise<void>;

export function SearchObjects(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Array<main.S3Object>>;

export function UploadFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UploadFiles(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;
