// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function CopyFolder(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CopyFolder'](arg1, arg2, arg3, arg4);
}

export function CopyObject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CopyObject'](arg1, arg2, arg3, arg4);
}

export function CreateBucket(arg1) {
  return window['go']['main']['App']['CreateBucket'](arg1);
}

export function CreateFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2, arg3);
}

export function DeleteFolder(arg1, arg2) {
  return window['go']['main']['App']['DeleteFolder'](arg1, arg2);
}

export function DeleteObject(arg1, arg2) {
  return window['go']['main']['App']['DeleteObject'](arg1, arg2);
}

export function DeleteObjects(arg1, arg2) {
  return window['go']['main']['App']['DeleteObjects'](arg1, arg2);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DownloadObject(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadObject'](arg1, arg2, arg3);
}

export function GetDownloadsFolder() {
  return window['go']['main']['App']['GetDownloadsFolder']();
}

export function GetPresignedURL(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPresignedURL'](arg1, arg2, arg3);
}

export function GetSavedConfig() {
  return window['go']['main']['App']['GetSavedConfig']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function ListBuckets() {
  return window['go']['main']['App']['ListBuckets']();
}

export function ListObjects(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListObjects'](arg1, arg2, arg3, arg4);
}

export function MoveFolder(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MoveFolder'](arg1, arg2, arg3, arg4);
}

export function MoveObject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MoveObject'](arg1, arg2, arg3, arg4);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenMultipleFilesDialog() {
  return window['go']['main']['App']['OpenMultipleFilesDialog']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchObjects(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchObjects'](arg1, arg2, arg3, arg4);
}

export function UploadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2, arg3);
}

export function UploadFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadFiles'](arg1, arg2, arg3);
}
